name: NGINX Validation
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test NGINX configs
    runs-on: ubuntu-latest
    env:
      working-directory: /home/runner/work/nginx-configs/nginx-configs

    steps:
      - name: Checkout Source Files
        uses: actions/checkout@v2
      - name: Install NGINX
        run: sudo apt-get install nginx
      - name: Test configs
        run: sudo nginx -c ${{env.working-directory}}/nginx/_testing.conf -t
